-- Сгенерировано из packages/ingest/src/themeRules.ts (scripts/gen-theme-map-sql.ts). Не редактировать вручную.
DELETE FROM theme_map;
INSERT INTO theme_map (pattern, match_type, theme_code, priority) VALUES
  ('здравоохран', 'ilike', 'health', 10),
  ('медицин', 'ilike', 'health', 10),
  ('поликлин', 'ilike', 'health', 10),
  ('больниц', 'ilike', 'health', 10),
  ('санитари', 'ilike', 'health', 12),
  ('ветер', 'ilike', 'animals', 15),
  ('ветсервис', 'ilike', 'animals', 15),
  ('отлов', 'ilike', 'animals', 15),
  ('бродяч', 'ilike', 'animals', 15),
  ('животн', 'ilike', 'animals', 15),
  ('собак', 'ilike', 'animals', 15),
  ('карантин', 'ilike', 'quarantine', 16),
  ('перемещение на территории', 'ilike', 'quarantine', 16),
  ('въезд-выезд', 'ilike', 'quarantine', 16),
  ('въезд, выезд', 'ilike', 'quarantine', 16),
  ('газоснаб', 'ilike', 'gas', 18),
  ('утечка газа', 'ilike', 'gas', 18),
  ('запах газа', 'ilike', 'gas', 18),
  ('отсутствует газ', 'ilike', 'gas', 18),
  ('отсутствие газа', 'ilike', 'gas', 18),
  ('чрезвычайн', 'ilike', 'emergency', 19),
  ('паводок', 'ilike', 'emergency', 19),
  ('подтопление', 'ilike', 'emergency', 40),
  ('затопление', 'ilike', 'emergency', 40),
  ('теплоснаб', 'ilike', 'heating', 20),
  ('теплотранзит', 'ilike', 'heating', 20),
  ('отоплен', 'ilike', 'heating', 20),
  ('горяч', 'ilike', 'heating', 25),
  ('канализац', 'ilike', 'sewer', 22),
  ('колодц', 'ilike', 'sewer', 24),
  ('колодец', 'ilike', 'sewer', 24),
  ('люк', 'ilike', 'sewer', 24),
  ('освещен', 'ilike', 'lighting', 26),
  ('фонар', 'ilike', 'lighting', 26),
  ('ночью отсутствует свет', 'ilike', 'lighting', 26),
  ('перегорев', 'ilike', 'lighting', 27),
  ('водоснаб', 'ilike', 'water', 30),
  ('отсутствие воды', 'ilike', 'water', 30),
  ('отсутствие водоснаб', 'ilike', 'water', 30),
  ('порыв воды', 'ilike', 'water', 30),
  ('утечка воды', 'ilike', 'water', 30),
  ('давления воды', 'ilike', 'water', 30),
  ('холодной воды', 'ilike', 'water', 30),
  ('холодное водоснаб', 'ilike', 'water', 30),
  ('водопровод', 'ilike', 'water', 32),
  ('электроснаб', 'ilike', 'electricity', 35),
  ('электроэнерг', 'ilike', 'electricity', 35),
  ('электрич', 'ilike', 'electricity', 38),
  ('напряжен', 'ilike', 'electricity', 40),
  ('кабел', 'ilike', 'electricity', 45),
  ('дорож', 'ilike', 'roads', 42),
  ('дороги', 'ilike', 'roads', 42),
  ('дорог,', 'ilike', 'roads', 42),
  ('асфальт', 'ilike', 'roads', 42),
  ('тротуар', 'ilike', 'roads', 42),
  ('светофор', 'ilike', 'roads', 42),
  ('семафор', 'ilike', 'roads', 42),
  ('проезжей части', 'ilike', 'roads', 42),
  ('открытие/закрытие дорог', 'ilike', 'roads', 42),
  ('яма', 'ilike', 'roads', 50),
  ('твердые бытовые отходы', 'ilike', 'waste', 44),
  ('тбо', 'ilike', 'waste', 44),
  ('вывоз мусора', 'ilike', 'waste', 44),
  ('убирают мусор', 'ilike', 'waste', 44),
  ('уборка мусора', 'ilike', 'waste', 46),
  ('мусорн', 'ilike', 'waste', 46),
  ('контейнер', 'ilike', 'waste', 48),
  ('транспорт', 'ilike', 'transport', 52),
  ('автобус', 'ilike', 'transport', 52),
  ('остановк', 'ilike', 'transport', 54),
  ('расписания', 'ilike', 'transport', 54),
  ('водител', 'ilike', 'transport', 54),
  ('кондуктор', 'ilike', 'transport', 54),
  ('перевозок', 'ilike', 'transport', 54),
  ('благоустрой', 'ilike', 'improvement', 60),
  ('сан очистка', 'ilike', 'improvement', 60),
  ('сан чистка', 'ilike', 'improvement', 60),
  ('очистка от снега', 'ilike', 'improvement', 60),
  ('очистка наледи', 'ilike', 'improvement', 60),
  ('уборка снега', 'ilike', 'improvement', 60),
  ('зелен', 'ilike', 'improvement', 62),
  ('насажден', 'ilike', 'improvement', 62),
  ('дерев', 'ilike', 'improvement', 62),
  ('траву', 'ilike', 'improvement', 62),
  ('парк', 'ilike', 'improvement', 64),
  ('сквер', 'ilike', 'improvement', 64),
  ('детская площадка', 'ilike', 'improvement', 64),
  ('спортивная', 'ilike', 'improvement', 64),
  ('городская среда', 'ilike', 'improvement', 66),
  ('субботник', 'ilike', 'improvement', 66),
  ('лифт', 'ilike', 'housing', 70),
  ('кондоминиум', 'ilike', 'housing', 70),
  ('кск', 'ilike', 'housing', 72),
  ('мжд', 'ilike', 'housing', 74),
  ('кровл', 'ilike', 'housing', 72),
  ('крыша', 'ilike', 'housing', 72),
  ('подъезд', 'ilike', 'housing', 74),
  ('жкх', 'ilike', 'housing', 76),
  ('бытовое обслуживание', 'ilike', 'housing', 76),
  ('восстановление после произв', 'ilike', 'housing', 76),
  ('ограждение', 'ilike', 'housing', 78),
  ('справочн', 'ilike', 'info', 85),
  ('справка', 'ilike', 'info', 85),
  ('любые справки', 'ilike', 'info', 85),
  ('информирование', 'ilike', 'info', 85),
  ('связь и информация', 'ilike', 'info', 85),
  ('телекоммуникац', 'ilike', 'info', 85),
  ('консультац', 'ilike', 'info', 88),
  ('переадресац', 'ilike', 'info', 88);
